### ISSUE TITLE
Room detail page missing crucial information

### ISSUE THREAD

**Issue by dangvuthang** [ManPhamQuang/COSC2769-rmit#117]
Room detail page does not provide information about when the room will start/`startedAt`, `status`. As the image below shows, no place on the page show information for `startedAt`, and `status`

![Screenshot (387)](https://user-images.githubusercontent.com/43143636/131695053-df11fd15-c560-4a6e-8d5e-91700994d77d.png)

**Comment by s3825455** [comment]
Please check my latest PR. TY!
